#a space-separated list of playbooks for tag capture
playbook_names_list: jvms.yml

#intermediate variable do not reference for use
all_tags: '{{tags_output.stdout_lines |join(",")| regex_replace("(.*?\sTAGS:\s)(\[)(.*?)(\])", "\3,")}}'

#string glob of all tags found for a given playbook
all_tags_no_space: '{{all_tags|regex_replace("(.*?,)\s", "\1")}}'

#final comma-separated list of tags. Includes trailing comma.
unique_tags_list: '{{all_tags_no_space.split(",")|unique | difference("codecheckout") | join(",") }}'


#hosts

#intermediate variable do not reference for use
all_hosts: '{{hosts_output.stdout_lines |join(",")| regex_replace("(.*?\s)(pattern:\s\[u'')(.*?)(''\],\s+)(hosts\s\(\d\):,)(\s+)([a-zA-Z\d]+)", "\7,\3,")| regex_replace("(.*?)(,{2,}\s*)(.*?)", "\1,\3") }}'

#final comma-separated list of hosts. Includes trailing comma.
unique_hosts_list: '{{all_hosts.split(",")|unique | join(",") }}'
